{
 "title": "Kinetic Dashboard",
 "tags": [
  "mogami",
  "mogami-api"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Solana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solana Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(mogami_api_transaction_make_transfer_solana_committed_counter_total{}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  },
  {
   "title": "Solana Confirmed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(mogami_api_transaction_make_transfer_solana_confirmed_counter_total{}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  },
  {
   "title": "Solana Finalized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(mogami_api_transaction_make_transfer_solana_finalized_counter_total{}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  },
  {
   "title": "Solana Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(mogami_api_transaction_make_transfer_solana_error_counter_total{}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  },
  { "title": "Kinetic Api Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Get App Config (Success)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(mogami_api_app_get_app_config_success_counter_total{}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  },
  {
   "title": "Get App Config (Error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(mogami_api_app_get_app_config_error_counter_total{}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  },
  { "title": "Kinetic Api App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Get Config (Success)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(mogami_api_app_get_app_config_success_counter_total{appKey=~\".+\"}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  },
  {
   "title": "Get Config (Error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(mogami_api_app_get_app_config_error_counter_total{}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  },
  { "title": "Kinetic Api Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Get App by Environment/Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(mogami_api_core_get_app_by_environment_index_counter_total{}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  },
  { "title": "Kinetic Api Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Make Transfer Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(mogami_api_transaction_make_transfer_request_counter_total{}[1m])",
     "legendFormat": "{{ appKey }}"
    }
   ]
  }
 ]
}