global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mogami-api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
