name: affected-lint

on:
  pull_request:
  push:
    branches:
      - dev
      - main

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false

jobs:
  main:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn nx affected --target=lint --parallel --max-parallel=3
  pr:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout pr
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn nx affected --target=lint --parallel --max-parallel=3
