name: build-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: nxpm
          POSTGRES_USER: nxpm
          POSTGRES_PASSWORD: nxpm
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node-version: [14.x]
        operating-system: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn format:check
