name: test-sdk-e2e

on:
  pull_request:
  push:
    branches:
      - dev
      - main

env:
  AUTH_USERS: 'alice|Kinetic@alice1|Admin,bob|Kinetic@bob1'
  API_URL: 'http://localhost:3000'
  APP_1_FEE_PAYER_BYTE_ARRAY: '[24,20,238,188,26,234,120,209,88,63,170,46,66,98,21,113,194,120,143,228,231,37,91,0,242,32,180,99,243,179,57,144,11,233,235,235,203,20,105,33,47,140,152,253,12,148,72,175,141,253,242,110,225,110,21,211,118,87,111,206,208,166,190,78]'
  APP_1_NAME: 'App 1'
  COOKIE_DOMAINS: 'localhost'
  COOKIE_NAME: '__session'
  CORS_ORIGINS: '*'
  DATABASE_URL: 'postgresql://prisma:prisma@localhost:5432/prisma?schema=kinetic'
  JWT_SECRET: 'KineticJwtSecret!'
  NX_CLOUD_DISTRIBUTED_EXECUTION: false
  SOLANA_DEVNET_RPC_ENDPOINT: 'http://localhost:8899'
  SOLANA_DEVNET_MINT_KIN: '*MoGaMuJnB3k8zXjBYBnHxHG47vWcW3nyb7bFYvdVzek,5,Kin'
  SOLANA_DEVNET_MINT_KIN_AIRDROP_SECRET_KEY: '[24,20,238,188,26,234,120,209,88,63,170,46,66,98,21,113,194,120,143,228,231,37,91,0,242,32,180,99,243,179,57,144,11,233,235,235,203,20,105,33,47,140,152,253,12,148,72,175,141,253,242,110,225,110,21,211,118,87,111,206,208,166,190,78]'
  SOLANA_DEVNET_MINT_USDC: '*USDzo281m7rjzeZyxevkzL1vr5Cibb9ek3ynyAjXjUM,2,USDC'
  SOLANA_DEVNET_MINT_USDC_AIRDROP_SECRET_KEY: '[24,20,238,188,26,234,120,209,88,63,170,46,66,98,21,113,194,120,143,228,231,37,91,0,242,32,180,99,243,179,57,144,11,233,235,235,203,20,105,33,47,140,152,253,12,148,72,175,141,253,242,110,225,110,21,211,118,87,111,206,208,166,190,78]'

jobs:
  main:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name != 'pull_request' }}
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: prisma
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      solana:
        image: ghcr.io/kin-labs/kinetic-solana-network:latest
        ports: ['8899:8899', '8900:8900']
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - run: yarn prisma db push
      - run: yarn nx e2e sdk-e2e --skip-nx-cache
  pr:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'pull_request' }}
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: prisma
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      solana:
        image: ghcr.io/kin-labs/kinetic-solana-network:latest
        ports: ['8899:8899', '8900:8900']
    steps:
      - uses: actions/checkout@v2
        name: Checkout pr
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - run: yarn prisma db push
      - run: yarn nx e2e sdk-e2e --skip-nx-cache
